server.port: 8080

addressClient:
  baseUrl: http://customer-service:8081

customerClient:
  baseUrl: http://customer-service:8081

spring:
  output:
    ansi:
      enabled: always
  application:
    name: api-service

  sleuth:
    otel:
      exporter:
        otlp:
          endpoint: http://jaeger-production-collector-headless.tracing-system.svc.cluster.local:4317

management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans
